USE CSE_B_312

CREATE TABLE CRICKET
( 
	PNAME VARCHAR(50),
	CITY VARCHAR(50),
	AGE INT
)

INSERT INTO CRICKET (PNAME,CITY,AGE)
VALUES
('SACHIN TENDULKAR','MUMBAI',30),
('RAHUL DRAVID','BOMBAY',35),
('M.S. DHONI','JHARKHAND',31),
('SURESH RAINA','GUJARAT',30)

-- LAB = A

--1. Create table Worldcup from cricket 
--with all the columns and data. 
SELECT * INTO WORLDCUP FROM CRICKET

--2.Create table T20 from cricket --with first two columns with no data.SELECT * INTO T20 FROM CRICKET UPDATE T20 SET PNAME = 'NULL', CITY = 'NULL'WHERE AGE = 30UPDATE T20 SET PNAME = NULL, CITY = NULLWHERE AGE = 35UPDATE T20 SET PNAME = NULL, CITY = NULLWHERE AGE = 31UPDATE T20 SET PNAME = NULL, CITY = NULLWHERE AGE = 30--3.  Create table IPL From Cricket with No DataSELECT * INTO IPL FROM CRICKET WHERE PNAME IS NULL AND CITY IS NULL AND AGE IS NULL-- LAB = BCREATE TABLE EMPLOYEE
( 
	ENAME VARCHAR(50),
	CITY VARCHAR(50),
	AGE INT
)INSERT INTO EMPLOYEE(ENAME,CITY,AGE)
VALUES
('JAY PATEL','RAJKOT',30),
('RAHUL DAVE','SURAT',35),
('JEET PATEL','BARODA',31),
('VIJAY RAVAL','RAJKOT',30)--1. Create table Employee_detail from Employee --with all the columns and data. SELECT * INTO EMPLOYEE_DETAILS FROM EMPLOYEE--2. Create table Employee_data from Employee --with first two columns with no data.SELECT * INTO EMPLOYEE_DATA FROM EMPLOYEEUPDATE EMPLOYEE_DATA SET ENAME = NULL, CITY = NULLWHERE AGE = 30UPDATE EMPLOYEE_DATA SET ENAME = NULL, CITY = NULLWHERE AGE = 35UPDATE EMPLOYEE_DATA SET ENAME = NULL, CITY = NULLWHERE AGE = 31UPDATE EMPLOYEE_DATA SET ENAME = NULL, CITY = NULLWHERE AGE = 30--3 Create table Employee_info from Employee with no DataSELECT * INTO EMPLOYEE_INFO FROM EMPLOYEEWHERE ENAME IS NULL AND CITY IS NULL AND AGE IS NULL-- LAB = C--1. Insert the Data into Employee_info from Employee --whose CITY is RajkotINSERT INTO EMPLOYEE_INFO SELECT * FROM EMPLOYEE WHERE CITY = 'RAJKOT'--2. Insert the Data into Employee_info from Employee --whose age is more than 32.INSERT INTO EMPLOYEE_INFO SELECT * FROM EMPLOYEE WHERE AGE > 32